export { AboutSection } from "./AboutSection";
export { ClientsSection } from "./ClientsSection";
export { CtaSection } from "./CtaSection";
export { FaqSection } from "./FaqSection";
export { HeroSection } from "./HeroSection";
export { ProcessSection } from "./ProcessSection";
export { ServicesPreviewSection } from "./ServicesPreviewSection";
export { TestimonialsSection } from "./TestimonialsSection";
export { WhyChooseUsSection } from "./WhyChooseUsSection";
